### ISSUE TITLE
java.io.InvalidClassException: org.dmg.pmml.PMML; Incompatible class (SUID)

### ISSUE THREAD

**Issue by exp6** [jpmml/jpmml-android#1]
Since Android (DVM) doesn't support JAXB processing, I've serialized my PMML object on a native Java environment (JVM). My goal was to be able only to create the Evaluator and do the evaluation in my Android app by just sending the .pmml.ser file from another environment.

When the PMML object it's about to be deserialized on the Android side, this exception ocurred.

My question is: 

Is there another solution for this issue while I just want to evaluate PMML on an Android app, instead of using a JVM environment? 

I've being avoiding JAXB libraries for serializing/deserializing PMML object, but seems imposible. 

Also, I'm using Gradle for compiling, so Maven is not the solution for built .pmml.ser files.

Thanks in advanced.

**Comment by vruusmann** [comment]
> When the PMML object it's about to be deserialized on the Android side, this exception occurred.

This exception happens if the `model.pmml.ser` file was serialized using a different JPMML-Model library version than what is bundled into your Android App.

Currently,  the `pmml-android` module depends on JPMML-Evaluator 1.2.13, which in turn depends on JPMML-Model 1.2.12:
https://github.com/jpmml/jpmml-android/blob/master/pmml-android/pom.xml#L18 and 
https://repo1.maven.org/maven2/org/jpmml/jpmml-evaluator/1.2.13/jpmml-evaluator-1.2.13.pom (scroll down to the definition of `org.jpmml:pmml-model` dependency)

If you generate the `model.pmml.ser` file using JPMML-Model 1.2.12, then everything should work fine.

The JPMML-Android has been unmaintained for quite some time. Should update it to latest JPMML-Evaluator 1.3.X version, and see if it's possible to simplify its dependency structure.

Earlier today I was supporting another person on a very related matter:
https://github.com/jpmml/jpmml-model/issues/12

> I've being avoiding JAXB libraries for serializing/deserializing PMML object, but seems impossible.

Back in the day, I got JAXB deserialization working on Android (some 4.X platform?) in a very tightly controlled environment. This SER-file based approach seemed like a much easier thing to develop and maintain, but real life experience doesn't agree with it.

**Comment by exp6** [comment]
@vruusmann Thanks for the early reply. **I must say it worked!**

The problem was the pmml-model dependency that i was using in my JVM environment. Now I built again the .pmml.ser file and everything was OK. Thanks!

**Comment by ritterliu** [comment]
@exp6 Hi, maybe we have met same problems, could you tell me how do you solve it?
Below is my situation:
1. I have already built the "pmml-android-example-1.0-SNAPSHOT.apk" and have it installed on my phone, it works well.

2. Move "jpmml-android/pmml-android/target/pmml-android-1.0-SNAPSHOT.jar" and "jpmml-android/pmml-android-example/target/generated-sources/combined-assets/model.pmml.ser" into my android project "Hello".

3. Project "Hello" is my test project, and it built an APK successfully in Android M. (It is built inside Android OS source code by using "mmm")

4. But when the "Hello" runs, it will generate a force close, error logs below:

02-08 21:00:50.064 26342 26342 E AndroidRuntime: FATAL EXCEPTION: main
02-08 21:00:50.064 26342 26342 E AndroidRuntime: Process: com.example.hello, PID: 26342
02-08 21:00:50.064 26342 26342 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.view.View$DeclaredOnClickListener.onClick(View.java:4461)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.view.View.performClick(View.java:5207)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:21177)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:742)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5514)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
02-08 21:00:50.064 26342 26342 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at android.view.View$DeclaredOnClickListener.onClick(View.java:4456)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    ... 9 more
02-08 21:00:50.064 26342 26342 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.io.InvalidClassException: org.dmg.pmml.PMML; Incompatible class (SUID): org.dmg.pmml.PMML: static final long serialVersionUID =7684337200530848876L; but expected org.dmg.pmml.PMML: static final long serialVersionUID =4488905061911255163L;
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at com.example.hello.MainActivity.click(MainActivity.java:77)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    ... 11 more
02-08 21:00:50.064 26342 26342 E AndroidRuntime: Caused by: java.io.InvalidClassException: org.dmg.pmml.PMML; Incompatible class (SUID): org.dmg.pmml.PMML: static final long serialVersionUID =7684337200530848876L; but expected org.dmg.pmml.PMML: static final long serialVersionUID =4488905061911255163L;
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.io.ObjectInputStream.verifyAndInit(ObjectInputStream.java:2336)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1643)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at org.jpmml.model.SerializationUtil.deserialize(SerializationUtil.java:37)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at org.jpmml.model.SerializationUtil.deserializePMML(SerializationUtil.java:24)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at com.example.hello.EvaluatorUtilaa.createEvaluator(EvaluatorUtilaa.java:36)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at com.example.hello.MainActivity.createEvaluator(MainActivity.java:108)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    at com.example.hello.MainActivity.click(MainActivity.java:75)
02-08 21:00:50.064 26342 26342 E AndroidRuntime:    ... 11 more
02-08 21:00:50.068  2824  8383 W ActivityManager:   Force finishing activity com.example.hello/.MainActivity

It seems like "serialVersionUID" problem.
But I still don't know how to solve this problem.

About my environment:
The Android source code is M, and my phone is M too, the SDK version in "jpmml-android/pmml-android-example/pom.xml", I set 23 too.

The "model.pmml.ser" has been copy into my porject.
The "pmml-android-1.0-SNAPSHOT.jar" copy into my project too.

And add some lines into Android.mk:
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := pmml-android:libs/pmml-android-1.0-SNAPSHOT.jar
LOCAL_STATIC_JAVA_LIBRARIES += pmml-android

BTW:
I have tried many combinations of different jpmml-eveluator/model/plugin versions, the SUID problem still happens.
pmml-evaluator version:
https://github.com/jpmml/jpmml-android/blob/master/pmml-android/pom.xml#L18
// change to 1.2.15

pmml-model version:
https://github.com/jpmml/jpmml-android/blob/master/pmml-android/pom.xml#L30
// change to 1.2.17

pmml-maven-plugin version:
https://github.com/jpmml/jpmml-android/blob/master/pmml-android-example/pom.xml#L55
// change to 1.2.17

Could you give me some advice?

**Comment by exp6** [comment]
@ritterliu 

In my JVM environment (simple maven java application) I have this jpmml dependency:

```
<dependency>
    	<groupId>org.jpmml</groupId>
    	<artifactId>pmml-model</artifactId>
    	<version>1.2.12</version>
</dependency>
```

In my Android environment, I have the jpmml-android jar as a library. 

First, I built the jpmml-android project with maven (mvn clean install) and then, just put it as a library on my Android project with Gradle.

At first, the problem was the pom dependency in JVM environment that wasn't compatible with the Android ones. After I change the pom with the correct version (1.2.12), everything is working as expected.

Hope this could help for your issue. Cheers.

**Comment by ritterliu** [comment]
@exp6 Thank you for your reply. But still have some questions.
1. Which "model.pmml.ser" do you use in your android project?
I use the "model.pmml.ser" which is generated in "jpmml-android/pmml-android-example/target/generated-sources/combined-assets/model.pmml.ser", But fail to parse in my android project, got SUID error.

2. If you don't use the "jpmml-android/.../combined-assets/model.pmml.ser", how do you convert your PMML date to Java Serialization (SER) data?

**Comment by ritterliu** [comment]
Finally, I solve this problem.

When the "pmml-android-1.0-SNAPSHOT.jar" is built as "LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES" in Android OS， the obfuscate should be turned off.

So, in the "proguard.cfg", we should add:
 _-keep class org.** { *; }
 -dontwarn org.**
 -keep class com.google.** { *; }
 -dontwarn com.google.**_
 
Then， the "pmml-android-1.0-SNAPSHOT.jar" will not obfuscate, and it will work well.
